package com.csye6225.spring2020.courseservice.datamodel;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="course")
public class Course {
    private String id;
    private String courseId;
    private String courseName;
    private String professorId;
    private String taId;
    private String department;
    private String boardId;
    private List<String> enrolledStudents = new ArrayList<>();
    private List<String> lectures = new ArrayList<>();
    private List<String> rosterId;
    private String snsTopicArn;


    public Course() {

    }

    public Course(String courseId, String courseName, String professorId, String taId, String department, String boardId) {
        this.courseId = courseId;
        this.courseName = courseName;
        this.professorId = professorId;
        this.taId = taId;
        this.department = department;
        this.boardId = boardId;
    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBIndexHashKey(globalSecondaryIndexName="courseId-index",attributeName="courseId")
    public String getCourseId() {
        return courseId;
    }

    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }

    @DynamoDBAttribute(attributeName="courseName")
    public String getCourseName() {
        return courseName;
    }

    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    @DynamoDBAttribute(attributeName="professorId")
    public String getProfessorId() {
        return professorId;
    }

    public void setProfessorId(String professorId) {
        this.professorId = professorId;
    }

    @DynamoDBAttribute(attributeName="taId")
    public String getTaId() {
        return taId;
    }

    public void setTaId(String taId) {
        this.taId = taId;
    }

    @DynamoDBAttribute(attributeName="department")
    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    @DynamoDBAttribute(attributeName="boardId")
    public String getBoardId() {
        return boardId;
    }

    public void setBoardId(String boardId) {
        this.boardId = boardId;
    }

    public List<String> getEnrolledStudents() {
        return enrolledStudents;
    }

    public void setEnrolledStudents(List<String> enrolledStudents) {
        this.enrolledStudents = enrolledStudents;
    }

    public List<String> getLectures() {
        return lectures;
    }

    public void setLectures(List<String> lectures) {
        this.lectures = lectures;
    }

    @DynamoDBAttribute(attributeName="rosterId")
    public List<String> getRosterId() {
        return rosterId;
    }

    public void setRosterId(List<String> rosterId) {
        this.rosterId = rosterId;
    }
    @DynamoDBAttribute(attributeName="snsTopicArn")
    public String getSnsTopicArn() {
        return snsTopicArn;
    }

    public void setSnsTopicArn(String snsTopicArn) {
        this.snsTopicArn = snsTopicArn;
    }

    @DynamoDBAttribute(attributeName="rosterId")


    @DynamoDBIgnore
    @Override
    public String toString() {
        return "Course{" +
                "courseId='" + courseId + '\'' +
                ", courseName='" + courseName + '\'' +
                ", professorId='" + professorId + '\'' +
                ", taId='" + taId + '\'' +
                '}';
    }
}
